name: Build Arduino Sketch

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # We use the `arduino/setup-arduino-cli` action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
     # - name: Install Arduino CLI
     #   run: |
     #     curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
     #   shell: bash

      - name: Install required libraries
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "TFT_eSPI"
          arduino-cli lib install "WiFiManager"
        shell: bash
        
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp32:esp32:tinypico"
          platforms: |
            - name: esp32:esp32
              source-url: https://dl.espressif.com/dl/package_esp32_index.json

          sketch-paths: |
            - sketch
