name: Build Arduino Sketch

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
        shell: bash

      - name: Install required libraries
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "TFT_eSPI"
          arduino-cli lib install "WiFiManager"
        shell: bash

      - name: Compile Arduino sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:tinypico /github/workspace/
        shell: bash
