name: Build Arduino Sketch

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Download Arduino CLI
        run: |
          curl -fsSL https://downloads.arduino.cc/arduino-cli/arduino-cli_Linux_64bit.tar.gz -o arduino-cli.tar.gz
          tar -xzf arduino-cli.tar.gz
        shell: bash

      - name: Install Arduino CLI
        run: |
          sudo mv arduino-cli /usr/local/bin
          arduino-cli version
        shell: bash

      - name: Install required libraries
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "TFT_eSPI"
          arduino-cli lib install "WiFiManager"
        shell: bash
        
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp32:esp32:tinypico"
          platforms: |
            - name: esp32:esp32
              source-url: https://dl.espressif.com/dl/package_esp32_index.json

          sketch-paths: |
            - sketch
